In [1]:
# Cenário 01 - Criando um banco de dados SQL a partir de arquivos CSV

# Biblioteca
import pandas as pd

In [2]:
# Importando arquivo CSV
dados = pd.read_csv(filepath_or_buffer = "https://aluno.analisemacro.com.br/download/45589/?tmstv=1672743605",
                    sep = ";",
                    encoding = "latin_1"
        )
dados

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,...,NR_SECAO,CD_CARGO,DS_CARGO,NR_VOTAVEL,NM_VOTAVEL,QT_VOTOS,NR_LOCAL_VOTACAO,SQ_CANDIDATO,NM_LOCAL_VOTACAO,DS_LOCAL_VOTACAO_ENDERECO
0,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,211,7,DEPUTADO ESTADUAL,19191,FRANCISCO DE PAIVA MELO JUNIOR,1,1066,10001650024,ESCOLA LUIZA BATISTA DE SOUZA,"RUA ALFREDO THAUNAY CONJ. ESPERANÇA II, 276Q13..."
1,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,356,7,DEPUTADO ESTADUAL,19191,FRANCISCO DE PAIVA MELO JUNIOR,1,1155,10001650024,ESCOLA DOM HENRIQUE RUTH,RUA DO PURUS - 611 - JO¿O ALVES
2,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,196,7,DEPUTADO ESTADUAL,19191,FRANCISCO DE PAIVA MELO JUNIOR,9,1619,10001650024,ESCOLA PROFESSORA RAMONA M P DE CASTRO,"RUA PROJETADA, 344 - BAO VISTA"
3,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,495,7,DEPUTADO ESTADUAL,19191,FRANCISCO DE PAIVA MELO JUNIOR,16,2836,10001650024,CENTRO DE SAUDE CLAUDIA VITORINO,"RUA BAGUARI, 40,"
4,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,355,7,DEPUTADO ESTADUAL,19191,FRANCISCO DE PAIVA MELO JUNIOR,1,2186,10001650024,ESCOLA DOUTOR JOAO AGUIAR,"RUA ADERBAL BRASIL, 310 - CONJUNTO MANOEL JULIÃO"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277660,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,145,7,DEPUTADO ESTADUAL,45,Partido da Social Democracia Brasileira,2,1031,-3,ESCOLA BORGES DE AQUINO,RUA BEIRA RIO S/N
277661,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,145,6,DEPUTADO FEDERAL,13,Partido dos Trabalhadores,1,1031,-3,ESCOLA BORGES DE AQUINO,RUA BEIRA RIO S/N
277662,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,145,6,DEPUTADO FEDERAL,33,Partido da Mobilização Nacional,1,1031,-3,ESCOLA BORGES DE AQUINO,RUA BEIRA RIO S/N
277663,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,145,6,DEPUTADO FEDERAL,10,REPUBLICANOS,1,1031,-3,ESCOLA BORGES DE AQUINO,RUA BEIRA RIO S/N
277664,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,145,6,DEPUTADO FEDERAL,12,Partido Democrático Trabalhista,1,1031,-3,ESCOLA BORGES DE AQUINO,RUA BEIRA RIO S/N

In [6]:
# Criar banco de dados SQLite

# Biblioteca
from sqlalchemy import create_engine, inspect
banco_de_dados = create_engine("sqlite:///dados/votacao2022.sqlite")
conexao = banco_de_dados.connect()
conexao

In [7]:
# Armazenar dados do CSV como uma tabela a ser criada no banco SQL
dados.to_sql(name = "votacao_acre", con = conexao, index = False)

277665

In [8]:
# Cenário 2 - Consultando um banco de dados SQL

# Ver nomes das tabelas
inspecao = inspect(banco_de_dados)
inspecao.get_table_names()

['votacao_acre']

In [9]:
# Ver informações das colunas de uma tabela
inspecao.get_columns(table_name = "votacao_acre")

[{'name': 'DT_GERACAO',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'HH_GERACAO',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'ANO_ELEICAO',
  'type': BIGINT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'CD_TIPO_ELEICAO',
  'type': BIGINT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'NM_TIPO_ELEICAO',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'NR_TURNO',
  'type': BIGINT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'CD_ELEICAO',
  'type': BIGINT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'DS_ELEICAO',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'DT_ELEICAO',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'TP_ABRANGENCIA',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'SG_UF',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'SG_UE',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'NM_UE',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'CD_MUNICIPIO',
  'type': BIGINT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'NM_MUNICIPIO',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'NR_ZONA',
  'type': BIGINT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'NR_SECAO',
  'type': BIGINT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'CD_CARGO',
  'type': BIGINT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'DS_CARGO',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'NR_VOTAVEL',
  'type': BIGINT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'NM_VOTAVEL',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'QT_VOTOS',
  'type': BIGINT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'NR_LOCAL_VOTACAO',
  'type': BIGINT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'SQ_CANDIDATO',
  'type': BIGINT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'NM_LOCAL_VOTACAO',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'primary_key': 0},
 {'name': 'DS_LOCAL_VOTACAO_ENDERECO',
  'type': TEXT(),
  'nullable': True,
  'default': None,
  'primary_key': 0}]

In [10]:
# Importar tabela completa do banco SQL
pd.read_sql(sql = "votacao_acre", con = conexao)

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,...,NR_SECAO,CD_CARGO,DS_CARGO,NR_VOTAVEL,NM_VOTAVEL,QT_VOTOS,NR_LOCAL_VOTACAO,SQ_CANDIDATO,NM_LOCAL_VOTACAO,DS_LOCAL_VOTACAO_ENDERECO
0,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,211,7,DEPUTADO ESTADUAL,19191,FRANCISCO DE PAIVA MELO JUNIOR,1,1066,10001650024,ESCOLA LUIZA BATISTA DE SOUZA,"RUA ALFREDO THAUNAY CONJ. ESPERANÇA II, 276Q13..."
1,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,356,7,DEPUTADO ESTADUAL,19191,FRANCISCO DE PAIVA MELO JUNIOR,1,1155,10001650024,ESCOLA DOM HENRIQUE RUTH,RUA DO PURUS - 611 - JO¿O ALVES
2,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,196,7,DEPUTADO ESTADUAL,19191,FRANCISCO DE PAIVA MELO JUNIOR,9,1619,10001650024,ESCOLA PROFESSORA RAMONA M P DE CASTRO,"RUA PROJETADA, 344 - BAO VISTA"
3,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,495,7,DEPUTADO ESTADUAL,19191,FRANCISCO DE PAIVA MELO JUNIOR,16,2836,10001650024,CENTRO DE SAUDE CLAUDIA VITORINO,"RUA BAGUARI, 40,"
4,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,355,7,DEPUTADO ESTADUAL,19191,FRANCISCO DE PAIVA MELO JUNIOR,1,2186,10001650024,ESCOLA DOUTOR JOAO AGUIAR,"RUA ADERBAL BRASIL, 310 - CONJUNTO MANOEL JULIÃO"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277660,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,145,7,DEPUTADO ESTADUAL,45,Partido da Social Democracia Brasileira,2,1031,-3,ESCOLA BORGES DE AQUINO,RUA BEIRA RIO S/N
277661,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,145,6,DEPUTADO FEDERAL,13,Partido dos Trabalhadores,1,1031,-3,ESCOLA BORGES DE AQUINO,RUA BEIRA RIO S/N
277662,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,145,6,DEPUTADO FEDERAL,33,Partido da Mobilização Nacional,1,1031,-3,ESCOLA BORGES DE AQUINO,RUA BEIRA RIO S/N
277663,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,145,6,DEPUTADO FEDERAL,10,REPUBLICANOS,1,1031,-3,ESCOLA BORGES DE AQUINO,RUA BEIRA RIO S/N
277664,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,145,6,DEPUTADO FEDERAL,12,Partido Democrático Trabalhista,1,1031,-3,ESCOLA BORGES DE AQUINO,RUA BEIRA RIO S/N

In [13]:
# Realizar consulta SQL
pd.read_sql(
      sql = "SELECT NM_VOTAVEL, QT_VOTOS, NM_MUNICIPIO, NR_SECAO FROM votacao_acre WHERE NM_MUNICIpIO == 'RIO BRANCO'",
      con = conexao
      )

                                 NM_VOTAVEL  QT_VOTOS NM_MUNICIPIO  NR_SECAO
0            FRANCISCO DE PAIVA MELO JUNIOR         1   RIO BRANCO       211
1            FRANCISCO DE PAIVA MELO JUNIOR         9   RIO BRANCO       196
2            FRANCISCO DE PAIVA MELO JUNIOR        16   RIO BRANCO       495
3            FRANCISCO DE PAIVA MELO JUNIOR         1   RIO BRANCO       355
4            FRANCISCO DE PAIVA MELO JUNIOR         1   RIO BRANCO       215
...                                     ...       ...          ...       ...
152260                         REPUBLICANOS         1   RIO BRANCO       560
152261                        PROGRESSISTAS         1   RIO BRANCO       560
152262  Partido Republicano da Ordem Social         1   RIO BRANCO       560
152263                         REPUBLICANOS         1   RIO BRANCO       560
152264                              Podemos         1   RIO BRANCO       560

[152265 rows x 4 columns]

In [14]:
# Encerrar conexão com o banco SQL
conexao.close()
conexao