In [1]:
# Biblioteca
import pandas as pd

In [2]:
# Arquivo Excel offline
tabela = pd.read_excel(io = "dados/dados.xlsx")
tabela

          data     pib
0   1996-01-01   99.55
1   1996-04-01  100.44
2   1996-07-01  104.38
3   1996-10-01  103.30
4   1997-01-01  104.32
..         ...     ...
100 2021-01-01  171.54
101 2021-04-01  171.17
102 2021-07-01  171.28
103 2021-10-01  172.41
104 2022-01-01  174.13

[105 rows x 2 columns]

In [3]:
# Arquivo Excel online
tabela = pd.read_excel(io = "https://aluno.analisemacro.com.br/download/45802/?tmstv=1672918970")
tabela

          data     pib
0   1996-01-01   99.55
1   1996-04-01  100.44
2   1996-07-01  104.38
3   1996-10-01  103.30
4   1997-01-01  104.32
..         ...     ...
100 2021-01-01  171.54
101 2021-04-01  171.17
102 2021-07-01  171.28
103 2021-10-01  172.41
104 2022-01-01  174.13

[105 rows x 2 columns]

In [5]:
# Importação de determinada folha do Excel
tabela = pd.read_excel(io = "dados/dados.xlsx", sheet_name = "ibc_br")
tabela

# OU

tabela = pd.read_excel(io = "dados/dados.xlsx", sheet_name = 1)
tabela

          data  ibc_br
0   2003-01-01   96.15
1   2003-02-01   98.67
2   2003-03-01  103.41
3   2003-04-01  102.19
4   2003-05-01  100.30
..         ...     ...
233 2022-06-01  142.13
234 2022-07-01  149.62
235 2022-08-01  150.09
236 2022-09-01  145.26
237 2022-10-01  143.56

[238 rows x 2 columns]

In [10]:
# Importação de Excel especificando intervalo de linhas
tabela = pd.read_excel(io = "dados/PcambBCp.xlsx",
                       skiprows = 10,
                       nrows = 180,
                       names = ("ano", "mes", "reservas", "estoque", "swap", "outros", "total"),
                       header = None
                       )
tabela

,ano,mes,reservas,estoque,swap,outros,total
0,2008.0,Jan,187507.153378,0.0,22181.689685,316.306128,210005.149190
1,NaN,Fev,192901.820218,0.0,22611.267756,117.924210,215631.012184
2,NaN,Mar,195231.614870,0.0,22627.569639,734.455027,218593.639536
3,NaN,Abr,195766.858581,0.0,22182.366580,983.883236,218933.108397
4,NaN,Mai,197906.274052,0.0,22328.470465,718.792263,220953.536780
...,...,...,...,...,...,...,...
175,NaN,Ago,339664.040274,0.0,-101816.331772,-17600.551600,220247.156903
176,NaN,Set*,327579.914932,3000.0,-98488.550066,-17504.330851,214587.034015
177,NaN,Out,325546.137553,4000.0,-95495.564327,-16895.286490,217155.286736
178,NaN,Nov*,331504.671267,4000.0,-96957.284668,-17627.696068,220919.690531
179,NaN,Dez*,329523.006450,9000.0,-97843.510071,-18266.146482,222413.349897