In [ ]:
# Biblioteca
import pandas as pd

In [7]:
# Dados
# Impotação de CSV offline
tabela = pd.read_csv(filepath_or_buffer = "dados.csv")
tabela

           data     pib
0    1996-01-01   99.55
1    1996-04-01  100.44
2    1996-07-01  104.38
3    1996-10-01  103.30
4    1997-01-01  104.32
..          ...     ...
100  2021-01-01  171.54
101  2021-04-01  171.17
102  2021-07-01  171.28
103  2021-10-01  172.41
104  2022-01-01  174.13

[105 rows x 2 columns]

In [ ]:
# Impotação de CSV online
tabela = pd.read_csv(filepath_or_buffer = "https://analisemacro.com.br/download/39167/")
tabela

           data     pib
0    1996-01-01   99.55
1    1996-04-01  100.44
2    1996-07-01  104.38
3    1996-10-01  103.30
4    1997-01-01  104.32
..          ...     ...
100  2021-01-01  171.54
101  2021-04-01  171.17
102  2021-07-01  171.28
103  2021-10-01  172.41
104  2022-01-01  174.13

[105 rows x 2 columns]

In [10]:
# Impotação de CSV com separador
tabela = pd.read_csv(filepath_or_buffer = "dados_pv.csv", sep = ";", decimal = ",")
tabela

           data     pib
0    1996-01-01   99.55
1    1996-04-01  100.44
2    1996-07-01  104.38
3    1996-10-01  103.30
4    1997-01-01  104.32
..          ...     ...
100  2021-01-01  171.54
101  2021-04-01  171.17
102  2021-07-01  171.28
103  2021-10-01  172.41
104  2022-01-01  174.13

[105 rows x 2 columns]

In [12]:
# Impotação de CSV com codificação diferente do padrão
tabela = pd.read_csv(
    filepath_or_buffer = "https://aluno.analisemacro.com.br/download/45589/?tmstv=1672743605",
    sep = ";",
    encoding = "latin_1"
)
tabela

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,...,NR_SECAO,CD_CARGO,DS_CARGO,NR_VOTAVEL,NM_VOTAVEL,QT_VOTOS,NR_LOCAL_VOTACAO,SQ_CANDIDATO,NM_LOCAL_VOTACAO,DS_LOCAL_VOTACAO_ENDERECO
0,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,211,7,DEPUTADO ESTADUAL,19191,FRANCISCO DE PAIVA MELO JUNIOR,1,1066,10001650024,ESCOLA LUIZA BATISTA DE SOUZA,"RUA ALFREDO THAUNAY CONJ. ESPERANÇA II, 276Q13..."
1,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,356,7,DEPUTADO ESTADUAL,19191,FRANCISCO DE PAIVA MELO JUNIOR,1,1155,10001650024,ESCOLA DOM HENRIQUE RUTH,RUA DO PURUS - 611 - JO¿O ALVES
2,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,196,7,DEPUTADO ESTADUAL,19191,FRANCISCO DE PAIVA MELO JUNIOR,9,1619,10001650024,ESCOLA PROFESSORA RAMONA M P DE CASTRO,"RUA PROJETADA, 344 - BAO VISTA"
3,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,495,7,DEPUTADO ESTADUAL,19191,FRANCISCO DE PAIVA MELO JUNIOR,16,2836,10001650024,CENTRO DE SAUDE CLAUDIA VITORINO,"RUA BAGUARI, 40,"
4,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,355,7,DEPUTADO ESTADUAL,19191,FRANCISCO DE PAIVA MELO JUNIOR,1,2186,10001650024,ESCOLA DOUTOR JOAO AGUIAR,"RUA ADERBAL BRASIL, 310 - CONJUNTO MANOEL JULIÃO"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277660,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,145,7,DEPUTADO ESTADUAL,45,Partido da Social Democracia Brasileira,2,1031,-3,ESCOLA BORGES DE AQUINO,RUA BEIRA RIO S/N
277661,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,145,6,DEPUTADO FEDERAL,13,Partido dos Trabalhadores,1,1031,-3,ESCOLA BORGES DE AQUINO,RUA BEIRA RIO S/N
277662,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,145,6,DEPUTADO FEDERAL,33,Partido da Mobilização Nacional,1,1031,-3,ESCOLA BORGES DE AQUINO,RUA BEIRA RIO S/N
277663,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,145,6,DEPUTADO FEDERAL,10,REPUBLICANOS,1,1031,-3,ESCOLA BORGES DE AQUINO,RUA BEIRA RIO S/N
277664,01/11/2022,16:05:25,2022,2,ELEIÇÃO ORDINÁRIA,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,145,6,DEPUTADO FEDERAL,12,Partido Democrático Trabalhista,1,1031,-3,ESCOLA BORGES DE AQUINO,RUA BEIRA RIO S/N