In [1]:
# Importando Biblioteca
import pandas as pd

In [4]:
# Importação de arquivo JSON
# Offline
pd.read_json(path_or_buf = "C:/Users/Mateus de Barros/OneDrive/Documentos/Diversos/Educação/Analise_Macro/Python/Material_Aula/pad20/dados/dados.json")

            data      valor
0     28/11/1984  2828.0000
1     29/11/1984  2828.0000
2     30/11/1984  2881.0000
3     03/12/1984  2881.0000
4     04/12/1984  2881.0000
...          ...        ...
9554  16/01/2023     5.1115
9555  17/01/2023     5.1203
9556  18/01/2023     5.0909
9557  19/01/2023     5.2144
9558  20/01/2023     5.1986

[9559 rows x 2 columns]

In [5]:
#Online
pd.read_json(path_or_buf= "https://api.bcb.gov.br/dados/serie/bcdata.sgs.1/dados?formato=json")

             data      valor
0      28/11/1984  2828.0000
1      29/11/1984  2828.0000
2      30/11/1984  2881.0000
3      03/12/1984  2881.0000
4      04/12/1984  2881.0000
...           ...        ...
10093  12/03/2025     5.8268
10094  13/03/2025     5.8131
10095  14/03/2025     5.7419
10096  17/03/2025     5.7082
10097  18/03/2025     5.6852

[10098 rows x 2 columns]