In [1]:
# Bibliotecas
import pandas as pd

In [3]:
# Importar arquivos XML
# Online
pd.read_xml(path_or_buffer = "https://raw.githubusercontent.com/schoulten/credit/main/dados.xml")

,V,MC,MN,NC,NN,D1C,D1N,D2C,D2N,D3C,D3N,D4C,D4N
0,Valor,Unidade de Medida (Código),Unidade de Medida,Nível Territorial (Código),Nível Territorial,Brasil e Região Metropolitana (Código),Brasil e Região Metropolitana,Variável (Código),Variável,Mês (Código),Mês,"Geral, grupo, subgrupo, item e subitem (Código)","Geral, grupo, subgrupo, item e subitem"
1,0.21,2,%,1,Brasil,1,Brasil,63,IPCA - Variação mensal,202001,janeiro 2020,7169,Índice geral
2,0.25,2,%,1,Brasil,1,Brasil,63,IPCA - Variação mensal,202002,fevereiro 2020,7169,Índice geral
3,0.07,2,%,1,Brasil,1,Brasil,63,IPCA - Variação mensal,202003,março 2020,7169,Índice geral
4,-0.31,2,%,1,Brasil,1,Brasil,63,IPCA - Variação mensal,202004,abril 2020,7169,Índice geral
...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,-0.90,2,%,7,Região Metropolitana,4301,Porto Alegre - RS,63,IPCA - Variação mensal,202208,agosto 2022,7169,Índice geral
393,-0.46,2,%,7,Região Metropolitana,4301,Porto Alegre - RS,63,IPCA - Variação mensal,202209,setembro 2022,7169,Índice geral
394,0.76,2,%,7,Região Metropolitana,4301,Porto Alegre - RS,63,IPCA - Variação mensal,202210,outubro 2022,7169,Índice geral
395,0.42,2,%,7,Região Metropolitana,4301,Porto Alegre - RS,63,IPCA - Variação mensal,202211,novembro 2022,7169,Índice geral
396,0.56,2,%,7,Região Metropolitana,4301,Porto Alegre - RS,63,IPCA - Variação mensal,202212,dezembro 2022,7169,Índice geral

In [5]:
# Offline
pd.read_xml(path_or_buffer = "C:/Users/Mateus de Barros/OneDrive/Documentos/Diversos/Educação/Analise_Macro/Python/Material_Aula/pad21/dados/dados.xml")

,V,MC,MN,NC,NN,D1C,D1N,D2C,D2N,D3C,D3N,D4C,D4N
0,Valor,Unidade de Medida (Código),Unidade de Medida,Nível Territorial (Código),Nível Territorial,Brasil e Região Metropolitana (Código),Brasil e Região Metropolitana,Variável (Código),Variável,Mês (Código),Mês,"Geral, grupo, subgrupo, item e subitem (Código)","Geral, grupo, subgrupo, item e subitem"
1,0.21,2,%,1,Brasil,1,Brasil,63,IPCA - Variação mensal,202001,janeiro 2020,7169,Índice geral
2,0.25,2,%,1,Brasil,1,Brasil,63,IPCA - Variação mensal,202002,fevereiro 2020,7169,Índice geral
3,0.07,2,%,1,Brasil,1,Brasil,63,IPCA - Variação mensal,202003,março 2020,7169,Índice geral
4,-0.31,2,%,1,Brasil,1,Brasil,63,IPCA - Variação mensal,202004,abril 2020,7169,Índice geral
...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,-0.90,2,%,7,Região Metropolitana,4301,Porto Alegre - RS,63,IPCA - Variação mensal,202208,agosto 2022,7169,Índice geral
393,-0.46,2,%,7,Região Metropolitana,4301,Porto Alegre - RS,63,IPCA - Variação mensal,202209,setembro 2022,7169,Índice geral
394,0.76,2,%,7,Região Metropolitana,4301,Porto Alegre - RS,63,IPCA - Variação mensal,202210,outubro 2022,7169,Índice geral
395,0.42,2,%,7,Região Metropolitana,4301,Porto Alegre - RS,63,IPCA - Variação mensal,202211,novembro 2022,7169,Índice geral
396,0.56,2,%,7,Região Metropolitana,4301,Porto Alegre - RS,63,IPCA - Variação mensal,202212,dezembro 2022,7169,Índice geral